{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catapult-logmaker.serviceAccountName" . }}
  labels:
{{ include "catapult-logmaker.labels" . | nindent 4 }}
{{- end -}}
